### ISSUE TITLE
Open World

### ISSUE THREAD

**Issue by Ken1oD** [Liangbai2333/RealHomeHunt#1]
In openWorlds I specified - sc but when I write /rh create it displays an error 此 世界 没有 开放 领地.In server.properties i specified level-name=sc
What am I doing wrong?

**Comment by Liangbai2333** [comment]
Please change the world name to a world name which exists on your server, the sc world does not exist on your server, it is default.

**Comment by Ken1oD** [comment]
I put world doesn't work either

**Comment by Liangbai2333** [comment]
Do you create your residence in the world which you set?

**Comment by Ken1oD** [comment]
No how to do it?

**Comment by Liangbai2333** [comment]
You should teleport to the world first, then you can create your residence.
